### ISSUE TITLE
iree.importer not found in failing regression tests

### ISSUE THREAD

**Issue by not-jenni** [iree-org/iree-samples#60]
```ModuleNotFoundError: No module named 'iree.importer'``` is causing failures in multiple regression tests
https://github.com/iree-org/iree-samples/runs/7261304178?check_suite_focus=true

**Comment by ScottTodd** [comment]
This should be fixed by https://github.com/iree-org/iree/pull/9752 and https://github.com/iree-org/iree/releases/tag/candidate-20220710.200. Let's re-enable https://github.com/iree-org/iree-samples/actions/workflows/regression_tests.yml and trigger it to verify?

**Comment by not-jenni** [comment]
I re-ran https://github.com/iree-org/iree-samples/runs/7287329518?check_suite_focus=true and it failed due to an unrelated error ("No space left on device"), but locally installing https://github.com/iree-org/iree/releases/tag/candidate-20220710.200 and running the test suite on my machine worked

**Comment by ScottTodd** [comment]
Interesting... the IREE releases don't appear to have changed much in size. We could compare the sizes of other packages during the "Install Deps" step in that workflow between the last successful build and the one you linked.

**Comment by not-jenni** [comment]
The main difference I am seeing is that the failing runs download 3 more tf-nightly wheels, adding up to ~1.5 GB.  (The failing runs also download termcolor, absl-py, and immutabledict while the passing runs do not, but these add up to <150 KB so I don't think they are the problem)

**Comment by jpienaar** [comment]
The repetitive downloads seems fixed (https://github.com/iree-org/iree-samples/runs/7314331472?check_suite_focus=true) post switch to nightly TF in requirements and the original issue addressed.
