### ISSUE TITLE
[runtime-library] Xcode complains undefined symbols

### ISSUE THREAD

**Issue by wangkuiyi** [iree-org/iree-samples#98]
The landing of https://github.com/iree-org/iree-samples/pull/97 enabled the building and running of a simple iOS app in Objective-C that calls `iree_status_fprint`.

Then, I copy-n-pasted the content of https://github.com/iree-org/iree-samples/blob/main/runtime-library/test_api.c to replace the call to `iree_status_fprint`. However, Xcode complains undefined symbols in flatcc and cpuinfo.

<img width="1199" alt="Screenshot 2023-01-19 at 8 54 35 AM" src="https://user-images.githubusercontent.com/1548775/213507362-2dbeb2ed-dca2-46cc-ae4a-1e0cabebc89e.png">

The command `nm -C` confirms that these symbols are **not defined** in all the target frameworks.
   ```
   $ nm -C ~/w/l/ios-app-call-cmake-xcframework/SampleApp/iree.xcframework/ios-arm64/iree.framework/iree  | grep _cpuinfo_get_clusters_count
                 U _cpuinfo_get_clusters_count
   $ nm -C ~/w/l/ios-app-call-cmake-xcframework/SampleApp/iree.xcframework/ios-arm64-simulator/iree.framework/iree  | grep _cpuinfo_get_clusters_count
                 U _cpuinfo_get_clusters_count
   $ nm -C ~/w/l/ios-app-call-cmake-xcframework/SampleApp/iree.xcframework/macos-arm64/iree.framework/iree  | grep _cpuinfo_get_clusters_count
                 U _cpuinfo_get_clusters_count
   ```
According to https://stackoverflow.com/a/32232609/724872, the letter `U` means that the symbol is used in the code. If they are defined, we should have got a letter `T`.

The build of `test_api.c` into `./build/bin/iree_test` succeeded without complaining of undefined symbols.  And `nm -C` reveals that the symbols exist in the executable binary:
```
$ nm -C build/bin/iree_test | grep _cpuinfo_get_clusters_count
0000000100035998 T _cpuinfo_get_clusters_count
```

Xcode didn't complain about `iree` symbols. And `nm -C` confirms that these `iree` symbols exist in target frameworks.
```
$ nm -C ~/w/l/ios-app-call-cmake-xcframework/SampleApp/iree.xcframework/macos-arm64/iree.framework/iree  | grep iree_hal_driver_registry_enumerate
/Users/y/w/l/ios-app-call-cmake-xcframework/SampleApp/iree.xcframework/macos-arm64/iree.framework/iree:tracing.cc.o: no symbols
---------------- T _iree_hal_driver_registry_enumerate
```

**Comment by ScottTodd** [comment]
For cpuinfo, you can try to set `-DIREE_ENABLE_CPUINFO=OFF` in the CMake build. We do that on a few platforms where cpuinfo is not as feature-complete. (We're also tracking a task to remove our dep on cpuinfo completely: https://github.com/iree-org/iree/issues/8469)

**Comment by wangkuiyi** [comment]
It seems that this problem is not about LTO.

Currently, the build of the runtime library for macOS/iOS disables LTO.

I tried to rebuild all target frameworks, macOS, iOS, and iOS Simulator, after enabling LTO. xcodebuild cannot build the XCFramework from LTO-enabled target frameworks. So, I manually copied the static libraries from each rebulit framework into the XCFramework. After all these, Xcode still complains the above undefined symbols.

**Comment by wangkuiyi** [comment]
It seems that when building a static library, CMake does not merge its dependencies.

**Comment by wangkuiyi** [comment]
The following experiment confirmed the above reason and shows the way to the solution.

### Dependencies of `libiree.a`

The [debug output](https://github.com/iree-org/iree-samples/blob/cc06e16e3d3b7b485dc542497004463f8ee5bdf2/runtime-library/CMakeLists.txt#L67) from CMake lists the following dependent libraries, which we should merge into the final static library.
```
;tracy_client::runtime_impl;flatcc::parsing;cpuinfo
```

### Find the dependent static libraries

```
$ du -a build-ios-sim/ | grep '\.a$'
80	build-ios-sim//iree_core/third_party/cpuinfo/libcpuinfo.a
16	build-ios-sim//iree_core/third_party/cpuinfo/deps/clog/libclog.a
32	build-ios-sim//iree_core/build_tools/third_party/flatcc/libflatcc_parsing.a
```

### Copy the dependents into a framework of the XCFramework

My Xcode-generated iOS app is in the directory `APP_DIR=~/w/l/ios-app-call-cmake-xcframework/SampleApp/`.

I copied the XCFramework to `XCFRAMEWORK=$APP_DIR/iree.xcframework`.

The iOS simulator target framework is in `IOS_SIM_FRAMEWORK=$XCFRAMEWORK/ios-arm64-simulator/iree.framework`.

```
for i in $(du -a build-ios-sim/ | grep '\.a$' | cut -f 2); do cp $i $IOS_SIM_FRAMEWORK; done
```

### Merge them into the static library `iree`

```
cd $IOS_SIM_FRAMEWORK
mv iree libiree.a # We will overwrite the file iree
libtool -static -o iree libiree.a libcpuinfo.a libflatcc_parsing.a libclog.a
```

### The result

Now, we could successfully build and run the iOS app in the simulator.

<img width="1072" alt="Screenshot 2023-01-19 at 1 12 14 PM" src="https://user-images.githubusercontent.com/1548775/213560441-a697d009-2bee-4cfa-9d18-06e000abc383.png">

At the bottom of the screenshot, the All Output window displays the following content

```
Available driver: local-sync (Local execution using a lightweight inline synchronous queue)
Available driver: local-task (Local execution using the IREE multithreading task system)
```

which is returned by the call to `iree_hal_driver_registry_enumerate`.
